### Data Analysis using Python ###

In [2]:
import numpy as np

In [9]:
# Creating Arrays using Numpy
# 1 - dimensional array
arr1 = np.array([1, 2, 3, 4, 5])    
print(arr1)
print(arr1.shape)   # Returns the shape of the array

[1 2 3 4 5]
(5,)


In [11]:
arr1.reshape(1, 5)  # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [17]:
# 2 - dimensional array
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
print(f"Number of dimensions: {arr2.ndim}")


[[1 2 3 4 5]
 [2 3 4 5 6]]
Number of dimensions: 2


In [14]:
# Creating arrays using in-built functions
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
# Identity Matrix
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
# Universal Functions
arr = np.array([36, 60, 90, 120, 180])
print("Square Root:", np.sqrt(arr))
print("Exponential: ", np.exp(arr))
print("Sine: ", np.sin(arr))

Square Root: [ 6.          7.74596669  9.48683298 10.95445115 13.41640786]
Exponential:  [4.31123155e+15 1.14200739e+26 1.22040329e+39 1.30418088e+52
 1.48938420e+78]
Sine:  [-0.99177885 -0.30481062  0.89399666  0.58061118 -0.80115264]


In [26]:
## Slicing and Indexing
arr = np.array([[1, 2, 3 , 4], [5, 6, 7, 8], [4, 5, 6, 7]])
print("Array: \n", arr)
print(arr[1:, 2:])

Array: 
 [[1 2 3 4]
 [5 6 7 8]
 [4 5 6 7]]
[[7 8]
 [6 7]]


In [27]:
# Statistical Concept -> Normalization
# To have a mean of 0 and Standard Deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate mean and std_dev
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the Data
normalized_data = (data - mean) / std_dev
print("Normalized Data: ", normalized_data)

Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [34]:
# Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data[(data > 5) & (data < 9)])

[6 7 8]
